services:
  - type: web
    name: sms-bomber
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bomber:app
    envVars:
      - key: PORT
        value: 10000
