services:
  - type: web
    name: sms-bomber
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bomber:app --workers 1 --worker-class gevent --worker-connections 1000 --timeout 300 --keep-alive 10
    envVars:
      - key: PORT
        value: 10000
